import { Load, LoadStatus, FleetRecord, TrackingUpdate, Client, DailyRateRecord, Project, ProjectStatus } from './types';

export const MOCK_LOADS: Load[] = [
  { 
    id: 'PBC-001', 
    date: '2023-10-25',
    client: 'Indústria ABC Ltda',
    origin: 'São Paulo, SP', 
    destination: 'Rio de Janeiro, RJ', 
    driver: 'Carlos Silva', 
    vehicleType: 'Carreta Baú',
    truckPlate: 'ABC-1234',
    trailerPlate: 'XYZ-9876',
    weight: 12000, 
    companyValue: 4500.00,
    driverValue: 3000.00,
    finalValue: 1500.00,
    toll: 450.00,
    adValorem: 120.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-26',
    status: LoadStatus.IN_TRANSIT,
    observation: 'Carga frágil'
  },
  { 
    id: 'PBC-002', 
    date: '2023-10-24',
    client: 'Comércio XYZ',
    origin: 'Curitiba, PR', 
    destination: 'Porto Alegre, RS', 
    driver: 'Roberto Dias', 
    vehicleType: 'Sider',
    truckPlate: 'DEF-5678',
    trailerPlate: 'WVU-5432',
    weight: 8500, 
    companyValue: 3200.00,
    driverValue: 2000.00,
    finalValue: 1200.00,
    toll: 300.00,
    adValorem: 80.00,
    icms: true,
    pisConfins: false,
    forecastDate: '2023-10-25',
    deliveryDate: '2023-10-25',
    status: LoadStatus.DELIVERED,
    observation: ''
  },
  { 
    id: 'PBC-003', 
    date: '2023-10-26',
    client: 'Tech Solutions',
    origin: 'Belo Horizonte, MG', 
    destination: 'Salvador, BA', 
    driver: 'Mariana Souza', 
    vehicleType: 'Graneleiro',
    truckPlate: 'GHI-9012',
    trailerPlate: 'TSR-3210',
    weight: 15000, 
    companyValue: 8900.00,
    driverValue: 6000.00,
    finalValue: 2900.00,
    toll: 800.00,
    adValorem: 200.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-28',
    status: LoadStatus.DELAYED,
    observation: 'Aguardando liberação fiscal'
  },
  { 
    id: 'PBC-004', 
    date: '2023-10-27',
    client: 'Agro Business',
    origin: 'Goiânia, GO', 
    destination: 'Brasília, DF', 
    driver: 'Fernando Lima', 
    vehicleType: 'Truck',
    truckPlate: 'JKL-3456',
    trailerPlate: 'QPO-7654',
    weight: 5000, 
    companyValue: 1500.00,
    driverValue: 1000.00,
    finalValue: 500.00,
    toll: 100.00,
    adValorem: 40.00,
    icms: false,
    pisConfins: false,
    forecastDate: '2023-10-27',
    status: LoadStatus.PENDING,
    observation: ''
  },
  { 
    id: 'PBC-005', 
    date: '2023-10-25',
    client: 'Construtora Build',
    origin: 'Recife, PE', 
    destination: 'Natal, RN', 
    driver: 'Paulo Mendes', 
    vehicleType: 'Carreta Baú',
    truckPlate: 'MNO-7890',
    trailerPlate: 'NML-0987',
    weight: 7200, 
    companyValue: 2100.00,
    driverValue: 1400.00,
    finalValue: 700.00,
    toll: 150.00,
    adValorem: 50.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-26',
    status: LoadStatus.IN_TRANSIT,
    observation: ''
  },
  { 
    id: 'PBC-006', 
    date: '2023-10-25',
    client: 'Logística Global',
    origin: 'Campinas, SP', 
    destination: 'Santos, SP', 
    driver: 'Lucas Ferreira', 
    vehicleType: 'Container',
    truckPlate: 'PQR-1357',
    trailerPlate: 'LKJ-2468',
    weight: 22000, 
    companyValue: 1800.00,
    driverValue: 1200.00,
    finalValue: 600.00,
    toll: 200.00,
    adValorem: 45.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-25',
    deliveryDate: '2023-10-25',
    status: LoadStatus.DELIVERED,
    observation: ''
  },
  { 
    id: 'PBC-007', 
    date: '2023-10-23',
    client: 'Amazonense Ltda',
    origin: 'Manaus, AM', 
    destination: 'Boa Vista, RR', 
    driver: 'Ana Paula', 
    vehicleType: 'Graneleiro',
    truckPlate: 'STU-9753',
    trailerPlate: 'HGF-8642',
    weight: 18000, 
    companyValue: 12000.00,
    driverValue: 9000.00,
    finalValue: 3000.00,
    toll: 0.00,
    adValorem: 300.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-26',
    status: LoadStatus.IN_TRANSIT,
    observation: 'Estrada com trechos difíceis'
  },
  { 
    id: 'PBC-008', 
    date: '2023-10-28',
    client: 'Sul Têxtil',
    origin: 'Florianópolis, SC', 
    destination: 'São Paulo, SP', 
    driver: 'Ricardo Gomes', 
    vehicleType: 'Carreta Baú',
    truckPlate: 'VWX-2468',
    trailerPlate: 'DSA-1357',
    weight: 9000, 
    companyValue: 3800.00,
    driverValue: 2500.00,
    finalValue: 1300.00,
    toll: 350.00,
    adValorem: 90.00,
    icms: true,
    pisConfins: true,
    forecastDate: '2023-10-29',
    status: LoadStatus.PENDING,
    observation: ''
  },
];

export const MOCK_FLEET: FleetRecord[] = [
  { id: 'FL-001', driverName: 'Carlos Silva', truckPlate: 'ABC-1234', trailerPlate: 'XYZ-9876', truckType: 'Carreta Baú', ownershipType: 'Frota', capacity: 25000 },
  { id: 'FL-002', driverName: 'Roberto Dias', truckPlate: 'DEF-5678', trailerPlate: 'WVU-5432', truckType: 'Sider', ownershipType: 'Terceiro', capacity: 27000 },
  { id: 'FL-003', driverName: 'Mariana Souza', truckPlate: 'GHI-9012', trailerPlate: 'TSR-3210', truckType: 'Graneleiro', ownershipType: 'Frota', capacity: 32000 },
  { id: 'FL-004', driverName: 'Fernando Lima', truckPlate: 'JKL-3456', trailerPlate: 'QPO-7654', truckType: 'Truck', ownershipType: 'Terceiro', capacity: 14000 },
  { id: 'FL-005', driverName: 'Paulo Mendes', truckPlate: 'MNO-7890', trailerPlate: 'NML-0987', truckType: 'Carreta Baú', ownershipType: 'Frota', capacity: 25000 },
];

export const MOCK_CLIENTS: Client[] = [
  { id: 'CLI-001', companyName: 'Indústria ABC Ltda', productType: 'Eletrônicos', city: 'São Paulo, SP', paymentType: 'Boleto', paymentTerm: '30 dias', contact: 'comercial@abc.com' },
  { id: 'CLI-002', companyName: 'Comércio XYZ', productType: 'Varejo Geral', city: 'Curitiba, PR', paymentType: 'Depósito', paymentTerm: 'À vista', contact: '(41) 99999-9999' },
  { id: 'CLI-003', companyName: 'Tech Solutions', productType: 'Hardware', city: 'Belo Horizonte, MG', paymentType: 'Boleto', paymentTerm: '45 dias', contact: 'financeiro@tech.com' },
  { id: 'CLI-004', companyName: 'Agro Business', productType: 'Grãos', city: 'Goiânia, GO', paymentType: 'Depósito', paymentTerm: '15 dias', contact: 'agro@business.com' },
  { id: 'CLI-005', companyName: 'Construtora Build', productType: 'Material de Construção', city: 'Recife, PE', paymentType: 'Boleto', paymentTerm: '30/60 dias', contact: 'obras@build.com' },
];

export const MOCK_DAILY_RATES: DailyRateRecord[] = [
  {
    id: 'DR-001',
    clientName: 'Indústria ABC Ltda',
    driverName: 'Carlos Silva',
    truckPlate: 'ABC-1234',
    trailerPlate: 'XYZ-9876',
    arrivalDateTime: '2023-10-25T08:00',
    departureDateTime: '2023-10-26T10:00',
    totalHours: 26,
    dailyRateQuantity: 1,
    delayReason: 'Demora na conferência de nota fiscal',
    hasAttachment: true
  },
  {
    id: 'DR-002',
    clientName: 'Comércio XYZ',
    driverName: 'Roberto Dias',
    truckPlate: 'DEF-5678',
    trailerPlate: 'WVU-5432',
    arrivalDateTime: '2023-10-24T14:00',
    departureDateTime: '2023-10-24T17:30',
    totalHours: 3.5,
    dailyRateQuantity: 0,
    delayReason: 'Descarga padrão',
    hasAttachment: false
  }
];

export const MOCK_TRACKING_HISTORY: TrackingUpdate[] = [
  { id: 'TRK-1', loadId: 'PBC-001', timestamp: '2023-10-25T08:00:00', location: 'São Paulo, SP', status: 'Início de Viagem', distanceToDelivery: 430, notes: 'Saída da garagem' },
  { id: 'TRK-2', loadId: 'PBC-001', timestamp: '2023-10-25T10:30:00', location: 'São José dos Campos, SP', status: 'Em Trânsito', distanceToDelivery: 350 },
  { id: 'TRK-3', loadId: 'PBC-001', timestamp: '2023-10-25T14:15:00', location: 'Aparecida, SP', status: 'Parada para Almoço', distanceToDelivery: 280 },
  { id: 'TRK-4', loadId: 'PBC-007', timestamp: '2023-10-23T09:00:00', location: 'Manaus, AM', status: 'Início de Viagem', distanceToDelivery: 780 },
  { id: 'TRK-5', loadId: 'PBC-007', timestamp: '2023-10-24T18:00:00', location: 'Presidente Figueiredo, AM', status: 'Pernoite', distanceToDelivery: 650 },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'PROJ-001',
    projectName: 'Distribuição Nacional de Eletrônicos',
    clientName: 'Indústria ABC Ltda',
    scope: 'Gestão logística completa para a distribuição de 2.000 unidades de televisores para 15 capitais brasileiras.',
    totalValue: 150000,
    valuePerLoad: 10000,
    loadQuantity: 15,
    paymentTerms: '30/60/90 dias',
    startDate: '2023-09-01',
    deadline: '2023-12-20',
    status: ProjectStatus.COMPLETED,
    responsible: 'Ana Julia',
    notes: 'Projeto finalizado com sucesso, 2 dias antes do prazo.'
  },
  {
    id: 'PROJ-002',
    projectName: 'Operação Safra de Grãos',
    clientName: 'Agro Business',
    scope: 'Transporte de 50.000 toneladas de soja do Mato Grosso para o Porto de Santos.',
    totalValue: 850000,
    valuePerLoad: 17000,
    loadQuantity: 50,
    paymentTerms: 'Sinal de 20% + pagamentos semanais',
    startDate: '2023-10-15',
    deadline: '2024-01-30',
    status: ProjectStatus.IN_PROGRESS,
    responsible: 'Carlos Silva',
    notes: 'Acompanhamento diário de frota. Clima favorável.'
  },
  {
    id: 'PROJ-003',
    projectName: 'Fornecimento para Obra Civil',
    clientName: 'Construtora Build',
    scope: 'Entrega programada de cimento, areia e brita para obra em Recife, PE, durante 6 meses.',
    totalValue: 320000,
    valuePerLoad: 3200,
    loadQuantity: 100,
    paymentTerms: 'Faturamento mensal',
    startDate: '2023-11-01',
    deadline: '2024-05-01',
    status: ProjectStatus.PLANNING,
    responsible: 'Mariana Souza',
    notes: 'Aguardando cronograma final da construtora.'
  }
];