// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hsmphtqhdbtxcdkswhrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbXBodHFoZGJ0eGNka3N3aHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTk5NjIsImV4cCI6MjA4MDI3NTk2Mn0.ecYakV4BMggQL5UAGvAqOUPjtI1fd8P5H4cwKXn4Okc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);